on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:9.4
        name: database
      conjur:
        image: cyberark/conjur
        name: conjur
        env:
          DATABASE_URL: postgres://postgres@database/postgres
          CONJUR_DATA_KEY: testdatakey

    steps:
      - name: Check containers deployed
        run: docker ps -a