on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:9.4
      conjur:
        image: cyberark/conjur
        env:
          DATABASE_URL: postgres://postgres@database/postgres
          CONJUR_DATA_KEY: testdatakey
      client:
        image: cyberark/conjur-cli:5
        options: --entrypoint=[ "sleep", "infinity" ]

    steps:
      - name: Check containers deployed
        run: docker ps -a